config/routes.rb
Rails.application.routes.draw do
  root to: redirect('/latest')

  get :latest, to: 'latest_session#edit'
  patch :latest, to: 'latest_session#update'

  resources :practice_sessions
end

app/models/practice_session.rb
class PracticeSession < ActiveRecord::Base
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/latest_session_controller.rb
class LatestSessionController < ApplicationController
  def edit
    @practice_session = PracticeSession.order(created_at: :desc).first
  end

  def update
    @practice_session = PracticeSession.order(created_at: :desc).first

    if @practice_session.update(practice_session_params)
      redirect_to latest_path
    else
      render :edit, error: 'Validation errors!'
    end
  end

  private

  def practice_session_params
    params.require(:practice_session).permit(:goal, :result, :date)
  end
end

app/controllers/practice_sessions_controller.rb
class PracticeSessionsController < ApplicationController
  def index
    @practice_sessions = PracticeSession.order(created_at: :asc)
  end

  def create
    @practice_session = PracticeSession.new(practice_session_params)

    if @practice_session.save
      redirect_to practice_sessions_path
    else
      render :new, error: 'Validation errors!'
    end
  end

  def new
    @practice_session = PracticeSession.new
  end

  def edit
    @practice_session = PracticeSession.find(params[:id])
  end

  def update
    @practice_session = PracticeSession.find(params[:id])

    if @practice_session.update(practice_session_params)
      redirect_to practice_sessions_path
    else
      render :edit, error: 'Validation errors!'
    end
  end

  private

  def practice_session_params
    params.require(:practice_session).permit(:goal, :result, :date)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def date_month_day_year(date)
    return '' if date.nil?

    l(date, format: :month_day_year)
  end

  def markdown(text)
    markdown = Redcarpet::Markdown.new(Redcarpet::Render::HTML)
    markdown.render(text).html_safe
  end
end

app/helpers/practice_sessions_helper.rb
module PracticeSessionsHelper
end

app/views/latest_session/edit.html.erb
<header class="header">
  <h1>🎯 Latest Goal</h1>
  <%= link_to 'Edit', edit_practice_session_path(@practice_session), class: 'button' %>
</header>

<%= form_for @practice_session, url: latest_path do |f| %>
  <div class="form-group">
    <%= f.label :goal %>
    <%= markdown(@practice_session.goal) %>
  </div>

  <div class="form-group">
    <%= f.label :result %>
    <% if @practice_session.result.present? %>
      <%= markdown(@practice_session.result) %>
    <% else %>
      <%= f.text_area :result, class: 'form-control' %>
    <% end %>
  </div>

  <div class="form-group">
    <%= f.label :date %>
    <%= f.text_field :date,
                      class: 'form-control datepicker',
                      value: date_month_day_year(@practice_session.date) %>
  </div>

  <div class="form-group">
    <%= f.button 'Save', class: 'button' %>
  </div>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Practice</title>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
  
  <link href="https://fonts.googleapis.com/css?family=Work+Sans:400,600" rel="stylesheet">
  <%= stylesheet_link_tag    'application', media: 'all' %>
  <%= javascript_include_tag 'application' %>
  <%= csrf_meta_tags %>
  <%= favicon_link_tag 'favicon.png' %>
</head>
<body>
  <nav class="nav">
    <div class="nav__logo">Practice</div>

    <div>
      <%= active_link_to 'New Goal', new_practice_session_path, class: 'nav__link' %>
    </div>
    <div>
      <%= active_link_to 'Latest', latest_path, class: 'nav__link' %>
    </div>
    <div>
      <%= active_link_to 'Sessions', practice_sessions_path, class: 'nav__link', active: :exact %>
    </div>
  </nav>

  <main class="main">
    <%= yield %>
  </main>
</body>
</html>

app/views/practice_sessions/edit.html.erb
<header class="header">
  <h1>Edit Practice Session</h1>
</header>

<%= form_for @practice_session do |f| %>
  <div class="row form-group">
    <div class="col">
      <%= f.label :goal %>
      <%= f.text_area :goal, class: 'form-control' %>
    </div>

    <div class="col">
      <%= f.label :result %>
      <%= f.text_area :result, class: 'form-control' %>
    </div>
  </div>

  <div class="form-group">
    <%= f.label :date %>
    <%= f.text_field :date,
                      class: 'form-control datepicker',
                      value: date_month_day_year(@practice_session.date) %>
  </div>

  <div class="form-group">
    <%= f.button 'Save', class: 'button' %>
    <%= link_to 'Cancel', practice_sessions_path %>
  </div>
<% end %>

app/views/practice_sessions/index.html.erb
<header class="header">
  <%= link_to 'New Practice Session', new_practice_session_path, class: 'button' %>
</header>

<table class="table table-striped">
  <thead>
    <tr>
      <th>Date</th>
      <th>Goal</th>
      <th>Result</th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @practice_sessions.each do |practice_session| %>
      <tr>
        <td><%= date_month_day_year(practice_session.date) %></td>
        <td><%= markdown(practice_session.goal) %></td>
        <td><%= markdown(practice_session.result) %></td>
        <td><%= link_to 'Edit', edit_practice_session_path(practice_session) %></td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/practice_sessions/latest.html.erb
<h1>🎯 Latest Goal</h1>

<%= @practice_session.goal %>

app/views/practice_sessions/new.html.erb
<header class="header">
  <h1>New</h1>
</header>

<%= form_for @practice_session do |f| %>
  <div class="row form-group ">
    <div class="col">
      <%= f.label :goal %>
      <%= f.text_area :goal, class: 'form-control' %>
    </div>

    <div class="col">
      <%= f.label :result %>
      <%= f.text_area :result, class: 'form-control' %>
    </div>
  </div>

  <div class="form-group">
    <%= f.label :date %>
    <%= f.text_field :date, class: 'form-control datepicker' %>
  </div>

  <div class="form-group">
    <%= f.button 'Save', class: 'button' %>
    <%= link_to 'Cancel', practice_sessions_path %>
  </div>
<% end %>